#aliases for commonly used commands
alias ll="ls -lgth"
alias lla="ls -algth"
alias wcl="wc -l"
alias dotar="tar -czvf"
alias untar="tar -xzvf"
alias mnt="sudo mount -o vers=3"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get update"
alias ainstall="sudo apt-get install"
alias push="git push"
alias push="git pull"
alias commit="git commit -am"
