- name: set up local dev machine
  hosts: 127.0.0.1
  vars:
      home: "{{ lookup('env', 'HOME') }}"
      release: jammy
      username: "{{ lookup('env', 'USER') }}" 
  connection: local
  become: true
  roles:
      #- common
      #- git
      #- python
      - bash
      #- vim
      #- i3
