- name: install python packages
  apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
      with_items:
          - cmake
          - build-essential
          - python-dev
          - python3-dev
          - python-pip
          - python3-pip

- name: download miniconda installation file
  get_url:
      url = http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
      dest = /tmp/miniconda.sh
      mode = 0755

- name: install miniconda
  shell: /tmp/miniconda.sh
      executable=/bin/bash

- name: install jupyter notebook
  command: conda install -y jupyter

- name: install jupyter client for 2.7 (needed for vim-ipython)
  pip: jupyter_client
