- name: add PPA for polybar
  apt_repository:
    repo: ppa:kgilmer/speed-ricer

- name: install i3 dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libxcb1-dev
    - libxcb-keysyms1-dev
    - libpango1.0-dev
    - libxcb-util0-dev
    - libxcb-icccm4-dev
    - libyajl-dev
    - libstartup-notification0-dev
    - libxcb-randr0-dev
    - libev-dev
    - libxcb-cursor-dev
    - libxcb-xinerama0-dev
    - libxcb-xkb-dev
    - libxkbcommon-dev
    - libxkbcommon-x11-dev
    - autoconf
    - libxcb-xrm0
    - libxcb-xrm-dev
    - automake

- file:
    path: "{{ home }}/.i3"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- file:
    path: "{{ home }}/.i3/bin"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"

- name: copy i3 config
  copy:
    src: i3config
    dest: "{{ home }}/.i3/config"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: copy helper utils
  copy:
    src: "{{ item }}"
    dest: "{{ home }}/.i3/bin/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
      - cycle-wallpaper
      - brightness-up
      - brightness-down

- name: install i3 utils
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - i3blocks
      - feh

- name: install polybar
  apt:
      name: polybar
      state: present

- name: copy polybar helpers
  copy:
    src: "{{ item }}"
    dest: "{{ home }}/.config/polybar/"
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
      - launch.sh
      - pavolume.sh

- name: copy polybar config
  copy:
    src: polybarconfig
    dest: "{{ home }}/.config/polybar/config"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: install kitty terminal
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin

- name: copy kitty config
  copy:
    src: solarized_kitty.conf
    dest: "{{ home }}/.config/kitty/kitty-themes/themes/Solarized_Light.conf"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: copy dircolors config
  copy:
    src: dircolors
    dest: "{{ home }}/.dir_colors"
    owner: "{{ username }}"
    group: "{{ username }}"

