- name: copy over gitconfig
  copy:
      src: files/gitconfig
      dest: "{{ home }}/.gitconfig"
      owner: "{{ username }}"
      group: "{{ username }}"

- name: install GnuPG2
  apt:
    name: gnupg2
    state: present
    update_cache: True

- name: add key
  shell: gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

- name: install rvm
  shell: \curl -sSL https://get.rvm.io | bash -s stable

- name: install ruby 2.1.1
  command: rvm install 2.1.1

- name: use ruby 2.1.1 by default
  command: rvm --default use 2.1.1

- name: install git-smart gem
  gem:
    name: git-smart
