- name: update packages
  apt:
      name: "*"
      state: latest
      force_apt_get: true
      update_cache: true

- name: install common packages
  apt:
      name: "{{ item }}"
      state: present
      force_apt_get: true
  with_items:
    - htop
    - tmux
    - curl
    - tree
    - powertop
    - libcurl4-openssl-dev 
    - libxml2-dev
    - cmake
    - chromium-browser
    - arandr
    - xorg-dev
    - libglu1-mesa-dev
