- name: add Chromium repo
  apt_repository:
      repo: ppa:chromium-daily/stable
      state: present

- name: add Spotify repo
  apt_repository:
      repo: deb http://repository.spotify.com stable non-free
      state: present
      filename: spotify.list

- name: update packages
  apt:
      name: "*"
      state: latest
      update_cache: true

- name: install common packages
  apt:
      name: "{{ item }}"
      state: present
      with_items:
          - htop
          - tmux
          - curl
          - libcurl4-openssl-dev 
          - libxml2-dev
          - cmake
          - chromium-browser
          - google-chrome-stable
          - spotify-client
          - arandr
          - xorg-dev
          - libglu1-mesa-dev
