
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


# enable vi shortcuts for CLI editing
set -o vi

# command prompt customization
export CLICOLOR=1
export PS1="\[\e[00;30m\]\u|\W|*\$(git branch 2>/dev/null | grep '^*' | colrm 1 2)*|\$?>\[\e[0m\] "

export PATH="$PATH:~/bin/"
export PATH=$HOME/miniconda2/bin/:$PATH

source $HOME/.aliases
