if [ -f /etc/bash_completion ]; then
 . /etc/bash_completion
fi

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


# enable vi shortcuts for CLI editing
set -o vi

# command prompt customization
export CLICOLOR=1
export PS1="\[\e[00;30m\]\u|\W|*\$(git branch 2>/dev/null | grep '^*' | colrm 1 2)*|\$?>\[\e[0m\] "

export PATH="$PATH:~/bin/"
export PATH=$HOME/anaconda3/bin/:$PATH

source $HOME/.aliases

eval `dircolors $HOME/.dir_colors/dircolors`

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export GR_HOME="$HOME/src/ConsultingMD/"
export PYTHONPATH="$GR_HOME/pygrounds/:$PYTHONPATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/ssoi/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/ssoi/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/ssoi/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/ssoi/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

