- name: add PPA for neovim
  apt_repository:
    repo: ppa:neovim-ppa/unstable

- name: install vim
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - neovim
      - vim
      - vim-runtime
      - vim-gtk3
      - vim-tiny
      - vim-gui-common
      - silversearcher-ag
      - universal-ctags

- name: copy vimrc
  copy:
      src: files/vimrc
      dest: "{{ home }}/.vimrc"
      owner: "{{ username }}"
      group: "{{ username }}"

- name: set up .vim directory
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
  with_items:
    - "{{ home }}/.vim/autoload/" 
    - "{{ home }}/.vim/pack/dist/start/"

- name: install pathogen
  get_url:
      url: https://tpo.pe/pathogen.vim
      dest: "{{ home }}/.vim/autoload/" 
      owner: "{{ username }}"
      group: "{{ username }}"

- name: download plugins
  git:
      repo: "ssh://git@github.com/{{ item.user }}/{{ item.repo}}.git"
      dest: "{{ home }}/.vim/pack/dist/start/{{ item.repo}}"
      recursive: yes
  with_items:
      - { user: 'ctrlpvim', repo: 'ctrlp.vim' }
      - { user: 'tpope', repo: 'vim-fugitive' }
      - { user: 'Valloric', repo: 'YouCompleteMe', force: 'yes' }
      - { user: 'scrooloose', repo: 'nerdtree' }
      - { user: 'altercation', repo: 'vim-colors-solarized' }
      - { user: 'vim-airline', repo: 'vim-airline' }
      - { user: 'w0rp', repo: 'ale' }
      - { user: 'majutsushi', repo: 'tagbar' }
      - { user: 'ludovicchabant', repo: 'vim-gutentags' }
      - { user: 'Exafunction', repo: 'codeium.vim' }
  become: true
  become_user: "{{ username }}"

- name: install YouCompleteMe
  command: python3 install.py
  become: yes
  become_user: "{{ username }}"
  args:
      chdir: "{{ home }}/.vim/pack/dist/start/YouCompleteMe/"

- name: copy snippets directory
  copy:
      src: files/snippets
      dest: "{{ home }}/.vim/snippets"
      owner: "{{ username }}"
      group: "{{ username }}"

- name: set up nvim .config directory
  file:
    path: "{{ home }}/.config/nvim/"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
  tags: neovim

- name: copy neovim initvim
  copy:
      src: files/initvim
      dest: "{{ home }}/.config/nvim/init.vim"
      owner: "{{ username }}"
      group: "{{ username }}"
  tags: neovim

