- name: remove vim
  apt:
      name: "{{ item }}"
      state: absent
  with_items:
      - vim
      - vim-runtime
      - vim-gnome
      - vim-tiny
      - vim-gui-common

- name: install vim dependences
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - liblua5.1-dev
      - luajit
      - libluajit-5.1-2
      - libluajit-5.1-dev
      - python-dev
      - ruby-dev
      - libperl-dev
      - libncurses5-dev
      - libatk1.0-dev
      - libx11-dev
      - libxpm-dev
      - libxt-dev

- name: download latest vim source
  git:
      repo: https://github.com/vim/vim
      dest: /tmp/vim/

- name: configure vim installation
  shell: |
      ./configure --enable-multibyte --enable-perlinterp=dynamic --enable-rubyinterp=dynamic --with-ruby-command=/usr/bin/ruby --enable-pythoninterp=dynamic --with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu --enable-python3interp --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu --enable-luainterp --with-luajit --enable-cscope --enable-gui=auto --with-features=huge --with-x --enable-fontset --enable-largefile --disable-netbeans --with-compiledby="Sameer Soi" --enable-fail-if-missing chdir=/tmp/vim/ 

- name: make vim
  command: make chdir=/tmp/vim/ 
          
- name: install vim
  command: make install chdir=/tmp/vim/ 
  become: true

- name: copy vimrc
  copy:
      src: files/vimrc
      dest: "{{ home }}/.vimrc"

- name: create pathogen directories
  file:
      path: "{{ home }}/.vim/{{ item }}"
      state: directory
  with_items:
      - autoload
      - bundle

- name: install pathogen
  get_url:
      url: https://tpo.pe/pathogen.vim
      dest: "{{ home }}/.vim/autoload/" 

- name: download plugins
  git:
      repo: "https://github.com/{{ item.user }}/{{ item.repo}}.git"
      dest: "{{ home }}/.vim/bundle/{{ item.repo}}"
  with_items:
      - { user: 'ctrlpvim', repo: 'ctrlp.vim' }
      - { user: 'tpope', repo: 'vim-fugitive' }
      - { user: 'davidhalter', repo: 'jedi-vim' }
      - { user: 'scrooloose', repo: 'nerdtree' }
      - { user: 'altercation', repo: 'vim-colors-solarized' }
      - { user: 'vim-airline', repo: 'vim-airline' }

